project:
  type: website
  output-dir: docs

website:
  title: "Soto Quant Finance Studio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: projects  # Dropdown for multiple projects
        menu:
          - href: "projects/Problems-in-Probability-and-Finance.qmd"
            text: "Problems-in-Probability-and-Finance"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



